name 'allpack'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures allpack'
long_description 'Installs/Configures allpack'
version '0.1.2'
