# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef"

  config.vm.define "web1" do |web1|
    web1.vm.hostname = 'web1'
    web1.vm.network :private_network, ip: "192.168.8.12"
    web1.vm.provider :virtualbox do |vb|
      vb.memory = "512"
    end
  end
  
  config.vm.define "web2" do |web2|
    web2.vm.hostname = 'web2'
    web2.vm.network :private_network, ip: "192.168.8.13"
    web2.vm.provider :virtualbox do |vb|
      vb.memory = "512"
    end
  end  

  config.vm.define "db" do |db|
    db.vm.hostname = 'db'
    db.vm.network :private_network, ip: "192.168.8.14"
    db.vm.provider :virtualbox do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.hostname = 'haproxy'
    haproxy.vm.network :private_network, ip: "192.168.8.15"
    haproxy.vm.provider :virtualbox do |vb|
      vb.memory = "512"
    end
  end
  

end