# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "minikube" do |kube|
    kube.vm.hostname = "minikube"
    kube.vm.network "private_network", ip: "192.168.12.25"
    config.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "2048"]
       vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    kube.vm.provision "shell", inline: $script
  end

$script = <<SCRIPT
echo Updating your VM...
sudo apt-get update
echo Installing Minikube...
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.24.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
echo Installing Kubectl...
curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
echo Installing Docker...
wget -qO- get.docker.com | bash

echo I am joining NFS...
sudo apt-get install nfs-common -y
sudo mkdir -p /nfs/kubernetes
sudo mount 192.168.12.50:/var/nfs/kubernetes /nfs/kubernetes

SCRIPT

end
